### ISSUE TITLE
UI Not Available With New Update

### ISSUE THREAD

**Issue by TraindKilla** [taniwha/Extraplanetary-Launchpads#117] opened 2016-06-23 01:01 UTC
I can't seem to access the ui when I right click on a EL survey station since the KSP 1.1.3 update has been released.  Tried to reinstall the mod files but this didn't help.  Please fix, I absolutely love this mod!!

**Comment by tea-man** [comment] 2016-06-26 15:43
I can second this problem, although not on a fresh install (see attached gamedata.txt)
No access to EPL UI from any screen in game, either through right click, stock toolbar or Blizzy toolbar
No EPL right click functionality on any parts (resource conversion, etc.)
Tested on existing save, and new save with reinstallation of EPL

Problem started after update to KSP 1.1.3. 

[KSP.txt](https://github.com/taniwha/Extraplanetary-Launchpads/files/333659/KSP.txt)
[gamedata.txt](https://github.com/taniwha/Extraplanetary-Launchpads/files/333658/gamedata.txt)

**Comment by TraindKilla** [comment] 2016-06-29 00:13
So...this is what I've found out with a little more messing around.  The problem isn't just EL, it may not be EL at all.  I have had additional issues with module manager and think the problem may be more related to module manager than it is related to EL. I've been having problems with stock parts not loading correctly, more specifically  the "enhanced stabilizers".  When module manager is installed I cannot stage the stabilizers in the VAB and when a rocket is placed on the launchpad the stabilizers do not extend to the ground to suspend the rocket.  When module manager is not installed I do not have any issues with stock parts, however EL cannot function correctly without module manager.

**Comment by SarahLJP** [comment] 2016-07-19 03:54
I'm experiencing this same problem.

**Comment by BCAMLiveBait** [comment] 2016-07-22 14:07
> TraindKilla commented 24 days ago
> So...this is what I've found out with a little more messing around. The problem isn't just EL, it may not be EL at all. I have had additional issues with module manager and think the problem may be more related to module manager than it is related to EL. I've been having problems with stock parts not loading correctly, more specifically the "enhanced stabilizers". When module manager is installed I cannot stage the stabilizers in the VAB and when a rocket is placed on the launchpad the stabilizers do not extend to the ground to suspend the rocket. When module manager is not installed I do not have any issues with stock parts, however EL cannot function correctly without module manager.


I hadn't thought it was related but I am going to attempt to find a slightly older release of mod manager and try it. Ill post if it works of not.

**Comment by tea-man** [comment] 2016-07-23 14:06
While I never discovered the root cause of this, my suspicion is that certain mod updates have left a Module patch somewhere that throws a gremlin in with Module Manager.
While I haven't been able to recreate the fault, there was no issue with using my existing save with a fresh install and clean mods.

**Comment by BCAMLiveBait** [comment] 2016-07-24 02:51
I just completed 24 hours of updating windows 8.1 so it is current. this help in that there is no error being thrown about EL in the log file any more but I still do not have UI. I had loaded up a legacy ver of KSP and all my favorite mods and everything worked minus that only the LaunchPad2 UI would show up and that it would not build anything. you could get it to that point and then no progress was ever made. Now I tried to trouble shoot this with having the work shop filled with smart engineer kerbals and the productivity var was still at (0).... so. Im just frustrated on all accounts. EL had been on of the mods that make the game intoxicating for me. also. I did load up one of my vers of Linux and it would only allow me to run the 64bit ver as I have that processor. I suspect there is a way to run the 32bit ver on that system but it alludes me at the moment. so. for the next bit I am going to ignore that KSP exists until the modders and squad can come to some kind of non selfish agreement to either stick with 32 or to commit to a standardized way of implementing 64bit so that we can get back to playing this wonderful game vs pulling our hair out over childish fighting over something so feeble as memory address sizing.

**Comment by JimmyDurandWesolowski** [comment] 2016-07-25 18:27
@all Please check your `GameData` folder and ensure you have the latest Module Manager (2.6.25 at the time of writing). Also ensure you do not have any other `ModuleManager.<version>.dll` brought in by any other module.

**Comment by SarahLJP** [comment] 2016-07-25 18:29
I do have the latest version of MM.

**Comment by JimmyDurandWesolowski** [comment] 2016-07-25 19:16
@SarahLJP And you do not have any EL icon floating somewhere?

**Comment by SarahLJP** [comment] 2016-07-25 19:55
You mean in the toolbar? Nope.

**Comment by BCAMLiveBait** [comment] 2016-07-25 20:40
I have also made sure of all of this on my distro. I also have switched to running linux full time as windows had finally pushed that last button of mine with all of this. Sooo. for this open issue: I have taken the time to have another clean install with mm 2.6.25 (the latest one) in the GameData folder. I also have the most current release of the tool bar. as much as it complains that it is meant for 1.1.2 no other mod has had issues with it. I maintain the .x86 operation vs .x86_64 as to eliminate that as an issue. and I am getting no errors that would say that EL is failing (I will provide my log file.) I have even spent time running fresh installs with various releases of EL to see if I could get it to run. Nothing. The only time I have been able to get the UI is to run KSP 1.0.5 and even then, it didnt let me build as no mater what I did it was under the impression that there was ( 0 ) productivity. I dont know what has happened as I had played 1.0.5 when it was released and never had any problems with EL; in fact the whole reason for going threw the trouble of having the ver of ksp is to recreate the interplanetary colonization experience that I have fond memories of from back then. 

This is my log file:
[KSP.txt](https://github.com/taniwha/Extraplanetary-Launchpads/files/382418/KSP.txt)
This is a screen shot of the LaunchPad2:
![screenshot from 2016-07-25 13-25-44](https://cloud.githubusercontent.com/assets/20598706/17116567/38bf4d0e-526d-11e6-902f-bf7ddb60aebc.png)
This is a screen shot of my terminal output:
![screenshot from 2016-07-25 13-27-47](https://cloud.githubusercontent.com/assets/20598706/17116573/40f6815e-526d-11e6-9479-5b130344b262.png)

**Comment by JimmyDurandWesolowski** [comment] 2016-07-25 20:52
@SarahLJP No, in the screen, not attached to the toolbar. Mine is floating. Can you also check from the workshop interface to display the GUI?
@BCAMLiveBait From your log, I see that the Toolbar mode is having issue with the version. It expects KSP version 1.1.2 only.

**Comment by JimmyDurandWesolowski** [comment] 2016-07-25 20:57
@BCAMLiveBait
You really have issues with your version:
```
[ERR 13:23:18.197] ExperienceTrait: Cannot add effect 'ExSurveySkill' as it does not exist.
[ERR 13:23:18.198] ExperienceTrait: Cannot add effect 'ExConstructionSkill' as it does not exist.
[ERR 13:23:18.198] ExperienceTrait: Cannot add effect 'ExSurveySkill' as it does not exist.
```
I will see how I can share my x86_64 version I rebuilt.

**Comment by BCAMLiveBait** [comment] 2016-07-25 20:58
I am not seeing it in the VAB either and was able to get it in the VAB on that old distro that wouldnt build anything. 

I thaught that might of been part of the issue but I have no issues with any other mods as there is no newer ver of this. also I am seeing in this log output file that both toolbar and EL as listed like this:

[LOG 13:21:30.942] [ModuleManager] compiling list of loaded mods...
Mod DLLs found:
    Assembly-CSharp v0.0.0.0                         SHA256 ea6233f8fb5409dd61b989af8b73a57db072e0b28186a84b985d59841cd72491
    ModuleManager.2.6.25 v2.6.25.0                   SHA256 ad71b29cf92e88f6515a82a6e0e95f7361c993cb1955e836ca94c5e891854d5c
    MiniAVC v1.0.3.2                                 SHA256 9ee10c46cb6f86417f005046ae72fedda156e1d47c92febcb84c68f50e03f08a
    aaa_Toolbar v1.0.0.0 / v1.7.11.0                 SHA256 96c53d6a779ffebc6844ed92fc8ee5e37ab32432439d28ca3258ce1090ea95c9
    KAS v0.5.9.0 / v0.5.9 for KSP 1.1.3              SHA256 93f5c292d1d9e1ecdf6314a32ed04feaae83f0b4e5ef8efe3048cdc265154ad1
    MiniAVC v1.0.3.1                                 SHA256 6b3cc0606f225afbab50a8e49e409ccd21c7d9c746805de7b47091d2c74ab4be
    KIS v1.2.12.0 / v1.2.12 for KSP 1.1              SHA256 c89f256fcb1c07b63a35364f0421df1a7fd92b6f74c2975bdb7af7077366c4e4
    KSPDev_Utils v0.13.0.0 / v0.13.0 for KSP v1.1    SHA256 19c05f99deb5c356bb2b6dd92fdc8b4247bb3d1f484b8e8d4076d4acbac9b596
    MiniAVC v1.0.3.0                                 SHA256 3a74237363b4c9739208c0420ecc04ead93f10bed39e82acad822317ffe04cc3
    SaveUpgradePipeline.Scripts v1.0.0.2 / v1.0.0.21 SHA256 b7d9f2b7398a6ce4db5a3d077a298c24f073d9083d8209a24fdc7a6a95f693d7
Non-DLL mods added (:FOR[xxx]):
  Launchpad
  ExtraplanetaryLaunchpads
Mods by directory (sub directories of GameData):
  000_Toolbar
  Squad

**Comment by BCAMLiveBait** [comment] 2016-07-25 20:59
build ver of ksp or EL?

**Comment by JimmyDurandWesolowski** [comment] 2016-07-25 20:59
@BCAMLiveBait Toolbar expects KSP version to be 1.1.2.

**Comment by BCAMLiveBait** [comment] 2016-07-25 21:00
I understand that

**Comment by BCAMLiveBait** [comment] 2016-07-25 21:02
hmu on skype, then we can post what we figure out here in an effort to keep the clutter down. bcamlivebait on skype; im the one that show up in wasco, or

**Comment by JimmyDurandWesolowski** [comment] 2016-07-25 21:02
@SarahLJP Can you also send me your KSP log please?

**Comment by BCAMLiveBait** [comment] 2016-07-25 21:13
I have had it in the past but same effect. I also dont know if the one I have is anything new or incompatible so I didnt add it in; I only extracted the GameData folder from EL's distro as it came from this account.

**Comment by JimmyDurandWesolowski** [comment] 2016-07-25 21:14
@BCAMLiveBait Can you please check for this file?

**Comment by BCAMLiveBait** [comment] 2016-07-25 21:19
the whole directory is missing
I have a copy of that file from (I have no idea) that I can put in a Plugins directory if you would like me to try that.
hell. ill do that now and get another log file for you.
again. it was not in to distro from this site

**Comment by SarahLJP** [comment] 2016-07-25 21:19
@JimmyDurandWesolowski Is this what you mean?
[output_log.txt](https://github.com/taniwha/Extraplanetary-Launchpads/files/382478/output_log.txt)

**Comment by JimmyDurandWesolowski** [comment] 2016-07-25 21:47
@BCAMLiveBait Have you tried on Windows? Unfortunately, I cannot play on Linux, I cannot load any saved game.

**Comment by BCAMLiveBait** [comment] 2016-07-25 21:49
same results......
hmm..


[LOG 14:32:02.177] [ModuleManager] compiling list of loaded mods...
Mod DLLs found:
    Assembly-CSharp v0.0.0.0                         SHA256 ea6233f8fb5409dd61b989af8b73a57db072e0b28186a84b985d59841cd72491
    ModuleManager.2.6.25 v2.6.25.0                   SHA256 ad71b29cf92e88f6515a82a6e0e95f7361c993cb1955e836ca94c5e891854d5c
    MiniAVC v1.0.3.2                                 SHA256 9ee10c46cb6f86417f005046ae72fedda156e1d47c92febcb84c68f50e03f08a
    aaa_Toolbar v1.0.0.0 / v1.7.11.0                 SHA256 96c53d6a779ffebc6844ed92fc8ee5e37ab32432439d28ca3258ce1090ea95c9
    KAS v0.5.9.0 / v0.5.9 for KSP 1.1.3              SHA256 93f5c292d1d9e1ecdf6314a32ed04feaae83f0b4e5ef8efe3048cdc265154ad1
    MiniAVC v1.0.3.1                                 SHA256 6b3cc0606f225afbab50a8e49e409ccd21c7d9c746805de7b47091d2c74ab4be
    KIS v1.2.12.0 / v1.2.12 for KSP 1.1              SHA256 c89f256fcb1c07b63a35364f0421df1a7fd92b6f74c2975bdb7af7077366c4e4
    KSPDev_Utils v0.13.0.0 / v0.13.0 for KSP v1.1    SHA256 19c05f99deb5c356bb2b6dd92fdc8b4247bb3d1f484b8e8d4076d4acbac9b596
    MiniAVC v1.0.3.0                                 SHA256 3a74237363b4c9739208c0420ecc04ead93f10bed39e82acad822317ffe04cc3
    SaveUpgradePipeline.Scripts v1.0.0.2 / v1.0.0.21 SHA256 b7d9f2b7398a6ce4db5a3d077a298c24f073d9083d8209a24fdc7a6a95f693d7
_# Non-DLL mods added (:FOR[xxx]):
  Launchpad
  ExtraplanetaryLaunchpads
Mods by directory (sub directories of GameData):
  000_Toolbar
  Squad_

[LOG 14:32:02.236] [ModuleManager] Loading Physics.cfg

for some reason it is not uploading the log file this time but this is an excerpt from it

**Comment by BCAMLiveBait** [comment] 2016-07-25 21:51
I have the same trouble in windows. and the game also dose not run half as smooth of the same machine.

**Comment by BCAMLiveBait** [comment] 2016-07-25 21:51
I have the same trouble in windows. and the game also dose not run half as smooth of the same machine.

**Comment by BCAMLiveBait** [comment] 2016-07-25 21:51
I have the same trouble in windows. and the game also dose not run half as smooth of the same machine.

**Comment by JimmyDurandWesolowski** [comment] 2016-07-25 21:51
@BCAMLiveBait You can add the file to your Gist, and then put the reference here. This is quite easy for texte files. I checked on mine, and I have the same result, so I expect this to be the "normal" behavior. Can you check for the other errors (`[ERR 13:23:18.197] ExperienceTrait: Cannot add effect 'ExSurveySkill' as it does not exist.`)?

**Comment by JimmyDurandWesolowski** [comment] 2016-07-25 21:54
@SarahLJP You got the same issue:
```
ExperienceTrait: Cannot add effect 'ExSurveySkill' as it does not exist.
ExperienceTrait: Cannot add effect 'ExConstructionSkill' as it does not exist.
```
Can you also check for the DLL?

**Comment by BCAMLiveBait** [comment] 2016-07-25 21:57
I had and then I posted that excerpt. I do have those errors. I remember seeing them in All my logs ever since I have tried this KSP 1.1.3

---------------------------
[LOG 14:34:45.992] ExperienceSystem: Found 0 trait types
[LOG 14:34:46.001] ExperienceSystem: Found 9 effect types
[LOG 14:34:46.007] Game State Created.
[ERR 14:34:46.020] ExperienceTrait: Cannot add effect 'ExSurveySkill' as it does not exist.

[ERR 14:34:46.022] ExperienceTrait: Cannot add effect 'ExConstructionSkill' as it does not exist.

[ERR 14:34:46.022] ExperienceTrait: Cannot add effect 'ExSurveySkill' as it does not exist.

[LOG 14:34:46.035] ScenarioTypes: List Created 14 scenario types loaded from 10 loaded assemblies.
---------------------------
[LOG 14:34:51.781] UIMasterController: HideUI
[ERR 14:34:51.864] ExperienceTrait: Cannot add effect 'ExSurveySkill' as it does not exist.

[ERR 14:34:51.864] ExperienceTrait: Cannot add effect 'ExConstructionSkill' as it does not exist.

[ERR 14:34:51.865] ExperienceTrait: Cannot add effect 'ExSurveySkill' as it does not exist.

[LOG 14:34:51.916] [CustomConfigsManager] Setting moddeed tech tree as the active one
---------------------------
[LOG 14:35:17.719] Loading clip: KIS/Sounds/attachScrewdriver
[LOG 14:35:17.720] AddonLoader: Instantiating addon 'KISAddonCursor' from assembly 'KIS'
[LOG 14:35:17.720] AddonLoader: Instantiating addon 'KISAddonPickupInEditor' from assembly 'KIS'
[LOG 14:35:17.728] Loading persistent fields: type=KIS.KISAddonPickup, group=""
[LOG 14:35:17.728] Loading persistent fileds: db path=KIS/settings/KISConfig, group=""
[LOG 14:35:17.729] Loading 5 persistent fields: group="", node=KISConfig
[LOG 14:35:17.750] UIMasterController: HideUI
[LOG 14:35:17.819] ------------------- initializing editor mode... ------------------
[LOG 14:35:17.819] editor started
[ERR 14:35:17.823] ExperienceTrait: Cannot add effect 'ExSurveySkill' as it does not exist.

[ERR 14:35:17.823] ExperienceTrait: Cannot add effect 'ExConstructionSkill' as it does not exist.

[ERR 14:35:17.823] ExperienceTrait: Cannot add effect 'ExSurveySkill' as it does not exist.

[LOG 14:35:17.890] IconLoader awake
[WRN 14:35:19.264] HighlightingSystem : Framebuffer depth data is not available and can't be used to occlude highlighting. Highlighting occluders enabled.
[WRN 14:35:19.952] The referenced script on this Behaviour is missing!
[WRN 14:35:19.952] The referenced script on this Behaviour is missing!
[WRN 14:35:19.952] The referenced script on this Behaviour is missing!
[WRN 14:35:23.805] [UiApp] Awake: EngineersReport
[WRN 14:35:23.805] [UiApp] Awake: KSPedia
[LOG 14:35:23.805] [ApplicationLauncher] OnSceneLoadedGUIReady: scene EDITOR ShouldBeVisible() True ShouldBeOnTop() False iIsPositionedAtTop False
[LOG 14:35:23.811] Loading Depletion Nodes
[LOG 14:35:23.811] DepNodeCount:  0
[LOG 14:35:23.812] Loading Biome Nodes
[LOG 14:35:23.812] BiomeNodeCount:  0
[LOG 14:35:23.812] Loading Planet Nodes
[LOG 14:35:23.812] PlanetNodeCount:  0
[LOG 14:35:23.821] [ScenarioDestructibles]: Loading... 0 objects registered
[LOG 14:35:23.886] [UIApp] OnDestroy: ContractsApp
[LOG 14:35:32.124] [MessageSystem] Reposition 0.02 5120
[WRN 14:35:32.154] UIList: RemoveItem didn't find any item to remove.
[LOG 14:35:33.043] [UIApp] Adding EngineersReport to Application Launcher
[LOG 14:35:33.143] [UIApp] Adding KSPedia to Application Launcher
[LOG 14:35:33.157] [GenericAppFrame] Reposition 0.26 5126
[LOG 14:35:33.972] UIMasterController: ShowUI
[LOG 14:35:36.391] [MessageSystem] Save Messages
[LOG 14:35:36.447] Game State Saved to saves/default/persistent
[LOG 14:35:51.222] [Pre-Flight Check]: Checking for CraftWithinPartCountLimit: PASS!
[LOG 14:35:51.223] [Pre-Flight Check]: Checking for CraftWithinSizeLimits: PASS!
[LOG 14:35:51.223] [Pre-Flight Check]: Checking for CraftWithinMassLimits: PASS!
[LOG 14:35:51.224] [Pre-Flight Check]: Checking for ExperimentalPartsAvailable: PASS!
[LOG 14:35:51.224] [Pre-Flight Check]: Checking for CanAffordLaunchTest: PASS!
[LOG 14:35:51.224] [Pre-Flight Check]: Checking for FacilityOperational: PASS!
[LOG 14:35:51.224] [Pre-Flight Check]: Checking for NoControlSources: PASS!
[LOG 14:35:51.227] [Pre-Flight Check]: Checking for LaunchSiteClear: PASS!
[LOG 14:35:51.227] [Pre-Flight Check]: All Checks Complete. Go for Launch!
[LOG 14:35:51.266] Launching vessel from LaunchPad. Craft file: /home/livebait/FD/KSP/KSP_linux/KSP_Data/../saves/default/Ships/VAB/Auto-Saved Ship.craft
[LOG 14:35:51.266] [MessageSystem] Save Messages
[LOG 14:35:51.270] Game State Saved to saves/default/persistent
[LOG 14:35:51.272] UIMasterController: HideUI
[WRN 14:35:52.388] [HighLogic]: =========================== Scene Change : From EDITOR to FLIGHT (Async) =====================
[LOG 14:35:52.958] [UIApp] OnDestroy: KSPedia
[LOG 14:35:53.006] [UIApp] OnDestroy: EngineersReport
[LOG 14:35:53.340] UIMasterController: HideUI
[LOG 14:35:53.368] AddonLoader: Instantiating addon 'KIS_UISoundPlayer' from assembly 'KIS'
[LOG 14:35:53.368] Loading UI sounds for KIS...
[LOG 14:35:53.368] Loading clip: KIS/Sounds/bipwrong
[LOG 14:35:53.369] Loading clip: KIS/Sounds/click
[LOG 14:35:53.370] Loading clip: KIS/Sounds/attachScrewdriver
[LOG 14:35:53.370] AddonLoader: Instantiating addon 'KISAddonCursor' from assembly 'KIS'
[LOG 14:35:53.955] [Toolbar] [INFO] loading settings (game scene: FLIGHT)
[LOG 14:35:53.955] [Toolbar] [INFO] no toolbars in current game scene, adding default toolbar
[LOG 14:35:53.955] [Toolbar] [INFO] loading toolbar settings (toolbar '')
[WRN 14:35:55.444] The referenced script on this Behaviour is missing!
[WRN 14:35:55.563] The referenced script on this Behaviour is missing!
[WRN 14:35:55.576] The referenced script on this Behaviour is missing!
[WRN 14:35:55.578] The referenced script on this Behaviour is missing!
[LOG 14:35:57.500] UICanvasPrefabSpawner FlightUI spawning Flight
[WRN 14:35:57.564] [UiApp] Awake: ResourceDisplay
[LOG 14:35:57.836] UIMasterController: HideUI
[LOG 14:35:57.850] AddonLoader: Instantiating addon 'AeroGUI' from assembly 'KSP'
[LOG 14:35:57.862] AddonLoader: Instantiating addon 'KASAddonWinchGUI' from assembly 'KAS'
[LOG 14:35:57.865] AddonLoader: Instantiating addon 'KASAddonDebugTools' from assembly 'KAS'
[LOG 14:35:57.867] AddonLoader: Instantiating addon 'KASAddonControlKey' from assembly 'KAS'
[LOG 14:35:57.872] AddonLoader: Instantiating addon 'KIS_UISoundPlayer' from assembly 'KIS'
[LOG 14:35:57.872] Loading UI sounds for KIS...
[LOG 14:35:57.873] Loading clip: KIS/Sounds/bipwrong
[LOG 14:35:57.873] Loading clip: KIS/Sounds/click
[LOG 14:35:57.873] Loading clip: KIS/Sounds/attachScrewdriver
[LOG 14:35:57.873] AddonLoader: Instantiating addon 'KISAddonCursor' from assembly 'KIS'
[LOG 14:35:57.874] AddonLoader: Instantiating addon 'KISAddonPickupInFlight' from assembly 'KIS'
[LOG 14:35:57.876] Loading persistent fields: type=KIS.KISAddonPickup, group=""
[LOG 14:35:57.876] Loading persistent fileds: db path=KIS/settings/KISConfig, group=""
[LOG 14:35:57.877] Loading 5 persistent fields: group="", node=KISConfig
[LOG 14:35:57.877] AddonLoader: Instantiating addon 'KISAddonPointer' from assembly 'KIS'
[LOG 14:35:58.027] ------------------- initializing flight mode... ------------------
[ERR 14:35:58.031] ExperienceTrait: Cannot add effect 'ExSurveySkill' as it does not exist.

[ERR 14:35:58.031] ExperienceTrait: Cannot add effect 'ExConstructionSkill' as it does not exist.

[ERR 14:35:58.031] ExperienceTrait: Cannot add effect 'ExSurveySkill' as it does not exist.

[LOG 14:35:58.035] [MessageSystem] Save Messages
[LOG 14:35:58.046] Loading ship from file: /home/livebait/FD/KSP/KSP_linux/KSP_Data/../saves/default/Ships/VAB/Auto-Saved Ship.craft
[WRN 14:35:58.174] [Part]: PartModule TransferDialogSpawner at exLaunchPad2, index 8: index exceeds module count as defined in cfg.
Looking for TransferDialogSpawner in other indices...
[WRN 14:35:58.174] ...no TransferDialogSpawner module found on part definition. Skipping...
[LOG 14:35:58.177] Untitled Space Craft loaded!
[LOG 14:36:02.578] putting ship to ground: 14
[LOG 14:36:02.595] [Untitled Space Craft]: Ready to Launch - waiting to start physics...
[LOG 14:36:02.655] Crewmember Jebediah Kerman assigned to Launch Pad 2, seat # 0 (crew seat index: 0)
[LOG 14:36:02.655] Crewmember Bill Kerman assigned to Launch Pad 2, seat # 1 (crew seat index: 1)
[LOG 14:36:02.656] [FLIGHT GLOBALS]: Switching To Vessel Untitled Space Craft ---------------------- 
[LOG 14:36:02.660] setting new dominant body: Kerbin
---------------------------

**Comment by SarahLJP** [comment] 2016-07-25 22:01
@JimmyDurandWesolowski Check for what DLL?

**Comment by JimmyDurandWesolowski** [comment] 2016-07-25 22:01
@BCAMLiveBait Can you post the full version, as you did before?

**Comment by BCAMLiveBait** [comment] 2016-07-25 22:12
Im trying but it is always stalling for some reason. i am about to do a fresh reboot just to eliminate everything

**Comment by BCAMLiveBait** [comment] 2016-07-25 22:29
Im getting no where with the upload here. can you suggest something that would work?

**Comment by BCAMLiveBait** [comment] 2016-07-25 22:50
I am just getting no where with this. it is like git hub is just not accepting files right now. I have to get off to a friends house to help her out in her garden so ill pick this back up tomorrow some time. I do hope it is just some weird blockage on githubs server of some kind and it will be fixed by the time I try again.
Thank you for all of your efforts and I hope we can get this figured out here together. I do love the mod and enjoy the game. Im not the most experienced programmer but I am thinking about looking into the code directly myself and learning something about c programming.

**Comment by BCAMLiveBait** [comment] 2016-07-25 23:18
[https://drive.google.com/open?id=0BxFiWSyh9RZVakw1RUtycUtSbDg](url)

**Comment by JimmyDurandWesolowski** [comment] 2016-07-26 11:31
@BCAMLiveBait From what I see, you have many errors:
`[ERR 14:30:40.544] AssemblyLoader: Exception loading 'KSPAPIExtensions':`
and more importantly in our case:
`[ERR 14:30:40.552] AssemblyLoader: Exception loading 'Launchpad':`
By the way, the mod does not come with this `Plugins/KSPAPIExtensions.dll`, does it?

**Comment by BCAMLiveBait** [comment] 2016-07-26 13:47
no it dosnt. i have had to dl it myself. i have done some reading on it and I normally place it in the GameData folder alongside the MM file.
That what what I was starting to come to in my logic also. although with out someone fixing it I would have to spend weeks just finding the issue let alone correcting the code and then I would have something I could never keep updated as the author of the mod changed things.
any hoo.
I know where to look in the windows ver for the binary folder but I dont see that in the Linux ver. I know I just sounded like a moron just then but I have been out of the C and Linux programming game for like a decade.
Are u asking for the game ver?

**Comment by JimmyDurandWesolowski** [comment] 2016-07-26 14:03
@BCAMLiveBait No worries. But you should put this one aside for the moment.
No I was asking about the binary you run? Or are you using steam, but it does not seem so? From what I remember, KSP under Linux still has its binaries extension set to '.exe'. So, are you running KSP.exe, or KSP_x86_64.exe or something else?

**Comment by BCAMLiveBait** [comment] 2016-07-26 14:14
put the KSPAPIextensions.dll aside????
I am starting it (as u can see from my terminal screen shot) with the commands (sudo ./KSP.x86)
I have found that if I dont run it in super that it locks up and just dosnt work.
come to think of it, yes, it is bundled in a KSP.exe file. here is a screen shot of my KSP_Linux directory.
![screenshot from 2016-07-26 07-11-21](https://cloud.githubusercontent.com/assets/20598706/17141226/379fb2ea-5300-11e6-8be8-80e76198c526.png)
and here is the continence of the buildID.txt file
build id = 01289
2016-06-21_20-12-27
Branch: master


I dont know if that might give any clues to what ver we are messing with as this is the first line of the log file: Kerbal Space Program - 1.1.3.1289 (LinuxPlayer)

**Comment by JimmyDurandWesolowski** [comment] 2016-07-26 14:42
@BCAMLiveBait Yeah, can you move out the `KSPAPIextensions.dll` from `GameData/Extraplanetary-Launchpads/Plugins` to your home for example?

**Comment by BCAMLiveBait** [comment] 2016-07-26 14:49
rgr. do u need a log file after i do that?

**Comment by JimmyDurandWesolowski** [comment] 2016-07-26 14:51
@BCAMLiveBait Yes, please.

**Comment by BCAMLiveBait** [comment] 2016-07-26 15:02
[KSP.txt](https://github.com/taniwha/Extraplanetary-Launchpads/files/384106/KSP.txt)
I just ran it and then wondered if u would need me to del the cash file for mm and run it again to see if that might provoke mm into compiling or loading anything that it hasnt in any beneficial way since I transferred the KSPAPIextentions.dll file out of and away from the game's directories.

**Comment by JimmyDurandWesolowski** [comment] 2016-07-26 16:06
@BCAMLiveBait `KSPAPIextentions.dll` is indeed out, but we still have the loading issue. Have you recompiled the EL module yourself? Is it from the latest archive?
I will check later if there is a tool to analyze those DLL under Linux.

**Comment by BCAMLiveBait** [comment] 2016-07-26 16:25
I have done nothing but dl EL from this site and follow the instructions of put the EL folder under GameData. so what is in the latest release is what I have on my computer.
I did move the KSPAPIextentions.dll folder away from where KSP interact with it.
I will Delete the cash file for MM and run KSP.x86 again for some more clean data in the log file.
oh.
remember u had me add the launchpad.dll file into a Plugins directory under EL in GameData.
I am starting to wonder if what I have is not in the best of shape as it did not come with what I DL'ed from here in this latest release of EL. I dont know where I found it but I had acquired on the sketchy advice that someone had said that the lack of it was the reason that the UI wasnt showing up; but again, MM says it isnt seeing a dll for EL. sooooo. hmm?
just to be clear. I have not gotten into any code of anything. the deepest I have gotten is just looking into log files.
Here is that new run of the KSP's log file: 
[KSP.txt](https://github.com/taniwha/Extraplanetary-Launchpads/files/384291/KSP.txt)

**Comment by JimmyDurandWesolowski** [comment] 2016-07-26 16:34
@BCAMLiveBait So, you did not had any `Launchpad.dll` in your `EL/Plugins` directory? That means that you did not download the module, you downloaded the sources... In the archive, is there a `source` folder? You should find in the forum the module archive in version 5.4.0, not the sources from Github. Here is the direct link to the archive:
http://taniwha.org/~bill/Extraplanetary_Launchpads_v5.4.0.zip

**Comment by BCAMLiveBait** [comment] 2016-07-26 16:37
ok. this would explain a lot.
and yes.
that is what I had done precisely.
I will dl from the link you have provided and run ksp again.
brb

**Comment by JimmyDurandWesolowski** [comment] 2016-07-26 16:40
@SarahLJP How is it on your side?

**Comment by SarahLJP** [comment] 2016-07-26 16:46
@JimmyDurandWesolowski I haven't tried to fix it. I'm afraid to mess with it. I was messing with mods recently. I broke something and lost some spacecraft. I think I'll just wait for an update and see if that fixes it. I would like to get it working, but it's not a big issue for me. Thanks for your attempt at helping me.

**Comment by BCAMLiveBait** [comment] 2016-07-26 17:00
ok. now I feel like the dumbest person alive
I am so sorry for all the grief I have caused.
I believe everyone that has proclaimed that EL dosnt work has done what I have done and then Ignorantly complained about it.
I want to apologize for acting like such and idiot about this.
In my defense I do want to say that github is what comes up when searching for EL and I did think that since it said it was a release that it what was to be available for dl and install. It was confusing why the source would of been with it as I know there are people that would not think and try to install that also,

**Comment by JimmyDurandWesolowski** [comment] 2016-07-26 17:09
@BCAMLiveBait No problem, we all do those kind of mistakes, and more often that we admit. My issue was very similar.

**Comment by JimmyDurandWesolowski** [comment] 2016-07-26 17:11
@SarahLJP If you backup everything properly, this should be fine. If you lost a vessel, it is certainly due to a module that you removed, and your spacecraft was relying on one or multiple parts from it.
So you need to backup modules, spacecrafts, and saves. I can also help you with this.

**Comment by JimmyDurandWesolowski** [comment] 2016-07-27 15:20
@TraindKilla I forgot to ask, what about you?

**Comment by SarahLJP** [comment] 2016-07-27 15:22
@JimmyDurandWesolowski Like I said, it's not that important. Thank you anyway.

**Comment by taniwha** [comment] 2016-12-31 02:07
closing as this should be a non-issue and is a few versions old

**Closed by taniwha** 2016-12-31 02:07 UTC
