### ISSUE TITLE
UI Broken (Not sure how to explain it)

### ISSUE THREAD

**Issue by dmh3333** [taniwha/Extraplanetary-Launchpads#129] opened 2017-05-29 19:38 UTC
I was building a base on Minmus and about to create a module when I attempted to open the menu. It works on other craft but some craft have this bug after quick loading or just exiting the game and getting back on. It says in the debug menu "Exeption: NullReferenceExeption: Object reference not set to the instance of an object" I'm using KSP 1.2.2. I've also tried new and old versions which is why I am using version 5.7.0. Please help! 
![asdadsw](https://cloud.githubusercontent.com/assets/29048590/26560453/59acdcf0-447c-11e7-8762-1ed04a46a59e.PNG)

**Comment by jmckinstry** [comment] 2017-09-08 04:20
I encountered this issue on KSP 1.3.0.1804, Extraplanetary Launchpads 5.8.2. I have multiple other mods installed that I'll find names and versions for on request. I can also provide a zip of the save file this is occurring on if desired.

This issue began manifesting when I loaded an existing on-Gilly installation for building parts. One of my four bounding stakes (-X, +X, -Z, +Z, all Bound) had disappeared (couldn't find it via [ or ]). Attempting to use the "Show UI" button resulted in an image similar to the above, with the exception showing in the console.

I couldn't find the stake via [ or ], but tracking had the stake, and I was able to load it. Found it floating 2.7KM above its original location with 0 velocity. Not sure why. Deleting it and then reloading the installation caused the UI to function correctly again. I did so twice to ensure that it was worth reporting.

Attached is my KSP.log file in the hopes that it'll help. The following line puts you near the excitement:
[LOG 23:15:05.950] [EL ST] RemoveStake KS-BBQ Survey Stake Gilly
[KSP.zip](https://github.com/taniwha/Extraplanetary-Launchpads/files/1286756/KSP.zip)


Hope that helps!

**Comment by taniwha** [comment] 2017-10-15 13:34
@dmh3333 I suspect that may have been fixed. 

@jmckinstry Yeah, going by the logs and looking at the code, it was due to that stake being outside the load range. I need to make that code a little more robust.

**Comment by SteveBenz** [comment] 2017-10-31 03:12
I hit this too on 5.8.0 and KSP 1.3.0.  Seems like the repro is:

1) Place a stake
2) Quicksave
3) Quickload
4) Open the EL Window

The work-around is:
1) Pick up the stake
2) Quicksave
3) Quickload
4) Place the stake again.

**Comment by SteveBenz** [comment] 2017-10-31 07:41
Wish the work around was that reliable...  It isn't.

**Comment by SteveBenz** [comment] 2017-10-31 07:41
Repro's in 5.9.

**Comment by doktorjet** [comment] 2018-02-02 20:10
02.02.2018 - the bug is still there

**Comment by taniwha** [comment] 2018-04-30 02:17
This may be fixed by 6.0.0. Please let me know.

**Comment by taniwha** [comment] 2018-10-16 10:39
Closing due to lack of additional feedback. If this bug is still present, please either reopen or create a new report.

**Closed by taniwha** 2018-10-16 10:39 UTC

**Comment by jmckinstry** [comment] 2018-10-16 21:04
Apologies for the lack of feedback, was out of the loop for some time.

I have been unable to reproduce this bug in 6.0.0. My original case no longer occurs. SteveBenz's repro steps no longer cause the bug for me either.

So, at a minimum, it works for me! Thanks!

**Comment by taniwha** [comment] 2018-10-18 08:47
Thank you :)

**Comment by portalfan04** [comment] 2021-05-28 21:51
Hi there,

Playing on latest version (6.8.3 i think, with KSP 1.11.2. According to people in the forums, it works just fine. I am getting plenty of issues running it with pathfinder however.) and I am also getting this error. It happens whenever I EVA a kerbal out of my gilly base and enter back in. 

To reproduce, I just load a save so its working again, and then EVA and it will break again. 

It seems that quicksaving and reloading is a fix for this, but its annoying having to do this every 30 seconds. 

See attached a screenshot of the error, and my KSP.log file. 

![screenshot12](https://user-images.githubusercontent.com/22401277/120044962-d329c980-c006-11eb-968b-768da263e641.png)

[log.zip](https://github.com/taniwha/Extraplanetary-Launchpads/files/6563468/log.zip)

Hope this helps! I'm  not sure if its because im running on 1.11.2, but I spent hours making this modpack from scratch and I'm not very tempted to downgrade after spending hours fixing scatterer configs.
